import tkinter
def clac_CI():
 p=int(p_amt.get())
 n=int(no_years.get())
 r=float(rate_int.get())
 amount=(p*(1+(r/100)) ** n) - p
 label_5["text"]=(str(round(amount,2)))
def clear_All():
 p_amt.delete(0,'end')
 no_years.delete(0,'end')
 rate_int.delete(0,'end')
 label_5["text"]=""
def close_process():
 quit()
form_CI=tkinter.Tk()
form_CI.title('Calculate Compound Interest')
label_1=tkinter.Label(form_CI,text="Enter Principle Amount : ")
p_amt=tkinter.Entry(form_CI)
label_2=tkinter.Label(form_CI,text="Enter No. of years : ")
no_years=tkinter.Entry(form_CI)
label_3=tkinter.Label(form_CI,text="Enter Rate of Interest : ")
rate_int=tkinter.Entry(form_CI)
label_4=tkinter.Label(form_CI,text="Compound Interst Amount : ")
label_5=tkinter.Label(form_CI,text="0")
submit_Btn=tkinter.Button(form_CI,text="Submit",command=clac_CI)
clear_Btn=tkinter.Button(form_CI,text="Clear ALL",command=clear_All)
close_Btn=tkinter.Button(form_CI,text="Close",command=close_process)
label_1.grid(row=0,column=1)
label_2.grid(row=2,column=1)
label_3.grid(row=4,column=1)
p_amt.grid(row=0,column=2)
no_years.grid(row=2,column=2)
rate_int.grid(row=4,column=2)
label_4.grid(row=6,column=1)
label_5.grid(row=6,column=2)
submit_Btn.grid(row=8,column=1)
clear_Btn.grid(row=8,column=2)
close_Btn.grid(row=8,column=3)
form_CI.mainloop()
